name: Deploy to Azure VM

on:
  push:
    branches:
      - main
    paths:
      - 'spring-server/**'
      - '.github/workflows/spring-deploy.yml'

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Set up JDK 21
        uses: actions/setup-java@v4
        with:
          java-version: '21'
          distribution: 'temurin'

      - name: Build with Gradle
        run: chmod +x gradlew
        working-directory: ./spring-server

      - name: Setup Gradle
        uses: gradle/actions/setup-gradle@v3

      - name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Build and push Docker image
        uses: docker/build-push-action@v5
        with:
          context: ./spring-server
          push: true
          tags: jklee3409/lecture-notes:latest

      - name: Deploy to Azure VM
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.AZURE_VM_HOST }}
          username: ${{ secrets.AZURE_VM_USERNAME }}
          key: ${{ secrets.AZURE_VM_SSH_PRIVATE_KEY }}
          script: |
            docker stop lecture-notes-server || true
            docker rm lecture-notes-server || true
            docker pull jklee3409/lecture-notes:latest
            docker run -d -p 80:8080 --name lecture-notes-server --restart always \
              -e SPRING_PROFILES_ACTIVE=prod \
              -e SPRING_DATASOURCE_URL="${{ secrets.PROD_DB_URL }}" \
              -e SPRING_DATASOURCE_USERNAME="${{ secrets.PROD_DB_USERNAME }}" \
              -e SPRING_DATASOURCE_PASSWORD="${{ secrets.PROD_DB_PASSWORD }}" \
              jklee3409/lecture-notes:latest